services:
  - type: web
    name: amacos-server
    env: node
    buildCommand: npm install
    startCommand: node index.js
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
